"""Add city to Hotels

Revision ID: ef98a9cb835a
Revises: 065c3ecdb4f8
Create Date: 2025-12-02 06:14:07.730631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef98a9cb835a'
down_revision: Union[str, Sequence[str], None] = '065c3ecdb4f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('city', sa.String(), nullable=False))
    op.create_index(op.f('ix_hotels_city'), 'hotels', ['city'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hotels_city'), table_name='hotels')
    op.drop_column('hotels', 'city')
    # ### end Alembic commands ###
